#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#    This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <https://www.gnu.org/licenses/>.

import gi

gi.require_version('Gimp', '3.0')
from gi.repository import Gimp

gi.require_version('GimpUi', '3.0')
from gi.repository import GimpUi

gi.require_version('Gegl', '0.4')
from gi.repository import Gegl
from gi.repository import GObject
from gi.repository import GLib
from gi.repository import Gio

gi.require_version('Gtk', '3.0')
from gi.repository import Gtk

gi.require_version('Gdk', '3.0')
from gi.repository import Gdk

gi.require_version("WebKit2", "4.0")
from gi.repository import WebKit2 as WebKit

import sys
from typing import Tuple
from struct import pack
from binascii import hexlify
from pathlib import Path

from gimp.image import display_image
import qrcode
import numpy as np


STATIC_PATH = (Path(__file__).parent / "static").absolute()
HEAD_TEXT = "Create a QR Code using qrcode python library."

QRCODE_ERROR_CORRECTION = {
    0: qrcode.ERROR_CORRECT_L,
    1: qrcode.ERROR_CORRECT_M,
    2: qrcode.ERROR_CORRECT_Q,
    3: qrcode.ERROR_CORRECT_H
}


def color_to_hex(color: Tuple[int, int, int]) -> str:
    return f"#{hexlify(pack('BBB', *color)).decode()}ff"


def gimp_rgb_to_hex(color: Gimp.RGB) -> str:
    r = int(255*color.r)
    g = int(255*color.g)
    b = int(255*color.b)
    return color_to_hex((r, g, b))


def gdk_color_to_hex(color: Gdk.Color) -> str:
    r, g, b = color.to_floats()
    r = int(255*r)
    g = int(255*g)
    b = int(255*b)
    return color_to_hex((r, g, b))



class PyDevClient(Gimp.PlugIn):
    ## Properties: parameters ##
    @GObject.Property(type=Gimp.RunMode,
                      default=Gimp.RunMode.NONINTERACTIVE,
                      nick="Run mode", blurb="The run mode")
    def run_mode(self):
        """Read-write integer property."""
        return self.runmode

    @run_mode.setter
    def run_mode(self, runmode):
        self.runmode = runmode

    def do_query_procedures(self):
        return ["python-create-qrcode"]

    def do_create_procedure(self, name):
        procedure = Gimp.Procedure.new(
            self,
            name,
            Gimp.PDBProcType.PLUGIN,
            self.run, None
        )

        # procedure.set_image_types("*")

        procedure.set_menu_label("QR Codes")
        # procedure.set_icon_name(GimpUi.ICON_GEGL)
        procedure.add_menu_path('<Image>/Python/Create')

        procedure.set_documentation(
            "Create a QR Code",
            "Create a QR Code",
            name
        )
        procedure.set_attribution("Ismael Benito", "Ismael Benito", "2021")

        procedure.add_argument_from_property(self, "run-mode")

        return procedure

    def run(self, procedure, args, run_data):

        GimpUi.init("python-create-qrcode")

        dialog = GimpUi.Dialog(
            use_header_bar=True,
            title="Create QR Code",
            role="python-create-qrcode"
        )

        dialog.add_button("Cancel", Gtk.ResponseType.CANCEL)
        dialog.add_button("Source", Gtk.ResponseType.APPLY)
        dialog.add_button("OK", Gtk.ResponseType.OK)

        dialog.set_default_size(720, 480)

        box = Gtk.Box(orientation=Gtk.Orientation.VERTICAL, spacing=2)
        dialog.get_content_area().add(box)
        box.show()

        label = Gtk.Label(label=HEAD_TEXT)
        box.pack_start(label, False, False, 1)
        label.show()

        grid_builder = Gtk.Builder()
        grid_builder.add_from_file((STATIC_PATH / "grid_builder.glade").as_posix())
        grid = grid_builder.get_object("main_grid")

        grid.get_parent().remove(grid)

        dialog.add(grid)
        dialog.get_content_area().add(grid)
        grid.show()

        dialog.show_all()


        contents = None

        if contents is not None:
            # import here when we have ensured requirements are installed.
            import markdown

            scrolled = Gtk.ScrolledWindow()
            scrolled.set_vexpand(True)
            box.pack_start(scrolled, True, True, 1)
            scrolled.show()

            webview = WebKit.WebView()
            webview.load_html(markdown.markdown(contents, extensions=['fenced_code']), None)
            scrolled.add(webview)
            webview.show()

        while True:
            response = dialog.run()
            if response == Gtk.ResponseType.OK:

                text = grid_builder.get_object("text_entry").get_text()
                version = int(grid_builder.get_object("version").get_value())
                box_size = int(grid_builder.get_object("box_size").get_value())
                border = int(grid_builder.get_object("border").get_value())
                ec_level = int(grid_builder.get_object("ec_level").get_active())

                # foreground = gimp_rgb_to_hex(Gimp.context_get_foreground()[-1])
                # background = gimp_rgb_to_hex(Gimp.context_get_background()[-1])

                foreground = gdk_color_to_hex(grid_builder.get_object("fcolor").get_color())
                background = gdk_color_to_hex(grid_builder.get_object("bcolor").get_color())

                qr = qrcode.QRCode(
                    version=version,
                    error_correction=QRCODE_ERROR_CORRECTION[ec_level],
                    box_size=box_size,
                    border=border
                )

                qr.add_data(text)
                qr.make()
                qr_img = qr.make_image(
                    fill_color=foreground,
                    back_color=background
                ).get_image()
                qr_img_arr = np.array(qr_img.convert("RGB")).astype(np.uint8)
                display_image(qr_img_arr)

                dialog.destroy()
                break
            elif response == Gtk.ResponseType.APPLY:
                url = "https://github.com/isman7/gimp-qrcode"
                Gio.app_info_launch_default_for_uri(url, None)
                continue
            else:
                dialog.destroy()
                return procedure.new_return_values(
                    Gimp.PDBStatusType.CANCEL,
                    GLib.Error()
                )

        # th.terminate()

        return procedure.new_return_values(Gimp.PDBStatusType.SUCCESS, GLib.Error())


Gimp.main(PyDevClient.__gtype__, sys.argv)
